-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 21:43:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_kurs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_kurs` ;

-- -----------------------------------------------------
-- Schema db_kurs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_kurs` DEFAULT CHARACTER SET utf8 ;
USE `db_kurs` ;

-- -----------------------------------------------------
-- Table `db_kurs`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurs`.`log` (
  `id` INT(11) NOT NULL,
  `baseline_date` DATE NOT NULL,
  `message` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_kurs`.`rawdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurs`.`rawdata` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `base_date` DATETIME NULL DEFAULT NULL,
  `source_id` INT(11) NULL DEFAULT NULL,
  `first_day_min_temp` DOUBLE NOT NULL,
  `first_day_max_temp` DOUBLE NOT NULL,
  `second_day_min_temp` DOUBLE NOT NULL,
  `second_day_max_temp` DOUBLE NOT NULL,
  `third_day_min_temp` DOUBLE NOT NULL,
  `third_day_max_temp` DOUBLE NOT NULL,
  `fourth_day_min_temp` DOUBLE NOT NULL,
  `fourth_day_max_temp` DOUBLE NOT NULL,
  `fifth_day_min_temp` DOUBLE NOT NULL,
  `fifth_day_max_temp` DOUBLE NOT NULL,
  `six_day_min_temp` DOUBLE NOT NULL,
  `six_day_max_temp` DOUBLE NOT NULL,
  `seven_day_min_temp` DOUBLE NOT NULL,
  `seven_day_max_temp` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2829
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_kurs`.`rawdata_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurs`.`rawdata_analysis` (
  `source` VARCHAR(45) NOT NULL,
  `baseline_date` DATE NOT NULL,
  `backward_deepness` INT(11) NOT NULL,
  `max_temp_diff` DOUBLE NULL DEFAULT NULL,
  `min_temp_diff` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`source`, `baseline_date`, `backward_deepness`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_kurs`.`sources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurs`.`sources` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `baseUrl` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_kurs`.`sources_aggregated_reliability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurs`.`sources_aggregated_reliability` (
  `source` VARCHAR(45) NOT NULL,
  `ratio` VARCHAR(45) NULL DEFAULT NULL,
  `backward_deepness` VARCHAR(45) NULL DEFAULT NULL,
  `log_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`source`),
  INDEX `log_id_idx` (`log_id` ASC),
  INDEX `source_idx` (`source` ASC),
  INDEX `logmsg_id_idx` (`log_id` ASC),
  CONSTRAINT `log_id`
    FOREIGN KEY (`log_id`)
    REFERENCES `db_kurs`.`log` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_kurs`.`sources_historical_reliability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurs`.`sources_historical_reliability` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `source` VARCHAR(45) NOT NULL,
  `baseline_date` DATE NOT NULL,
  `backward_deepness` INT(11) NOT NULL,
  `reliability_ratio` DOUBLE NOT NULL,
  PRIMARY KEY (`source`, `baseline_date`, `backward_deepness`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `db_kurs` ;

-- -----------------------------------------------------
-- procedure calc_aggregated_ratio
-- -----------------------------------------------------

DELIMITER $$
USE `db_kurs`$$
CREATE DEFINER=`springuser`@`localhost` PROCEDURE `calc_aggregated_ratio`()
Begin
	SET SQL_SAFE_UPDATES = 0;
	SET @totalSum = (select sum(reliability_ratio) from sources_historical_reliability);
	Update sources_aggregated_reliability aggr
	join (
			select source, (sum(reliability_ratio)/@totalSum) as ratio from sources_historical_reliability group by source) as tmp
		on aggr.source=tmp.source
    Set aggr.ratio = tmp.ratio;
    SET SQL_SAFE_UPDATES = 1;
End$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
